#define NOTION_VERSION NOTION_RELEASE
#define NOTION_API_VERSION NOTION_RELEASE

/** and for backwards-compatibility */
#define ION_RELEASE NOTION_RELEASE
#define ION_VERSION NOTION_RELEASE
#define ION_API_VERSION NOTION_RELEASE
