##
## mod_ionflux Makefile
##

# System-specific configuration is in system.mk
TOPDIR=.
include system.mk

######################################

INSTALL_SUBDIRS = mod_ionflux ionflux
SUBDIRS = $(INSTALL_SUBDIRS)

######################################

include $(TOPDIR)/build/rules.mk

######################################

