##
## mod_notionflux Makefile
##

# System-specific configuration is in system.mk
TOPDIR=..
include $(TOPDIR)/build/system-inc.mk

######################################

INSTALL_SUBDIRS = mod_notionflux notionflux
SUBDIRS = $(INSTALL_SUBDIRS)

######################################

include $(TOPDIR)/build/rules.mk

######################################

