macro(set_default name default)
	if(NOT DEFINED ${name})
		message("-- Defaulting ${name} to ${default}")
		set(${name} ${default})
	else()
		message("-- User set   ${name} to ${${name}}")
	endif()
endmacro()

set_default(ETCDIR etc/notion)
set_default(BINDIR bin)
set_default(SHAREDIR share/notion)
set_default(MANDIR share/man)
set_default(DOCDIR share/doc/notion)
set_default(LIBDIR lib)
set_default(MODULEDIR ${LIBDIR}/notion/mod)
set_default(LCDIR ${LIBDIR}/notion/lc)
set_default(EXTRABINDIR ${LIBDIR}/notion/bin)
set_default(VARDIR /var/cache/notion)
set_default(LOCALEDIR share/locale)
set_default(INCDIR include/notion)

set_default(CF_DRAG_TRESHOLD		2)
set_default(CF_DBLCLICK_DELAY		250)
set_default(CF_MAX_MOVERES_STR_SIZE	32)
set_default(CF_RESIZE_DELAY		1500)
set_default(CF_XMESSAGE			"xmessage -file ")
set_default(CF_EDGE_RESISTANCE		16)
set_default(CF_RAISE_DELAY		500)
set_default(CF_STATUSBAR_SYSTRAY_HEIGHT	24)
set_default(CF_VISIBILITY_CONSTRAINT	16)
set_default(CF_USERTIME_DIFF_CURRENT	2000)
set_default(CF_USERTIME_DIFF_NEW	4000)
set_default(CF_CURSOR_DEFAULT		XC_left_ptr)
set_default(CF_CURSOR_RESIZE		XC_sizing)
set_default(CF_CURSOR_MOVE		XC_fleur)
set_default(CF_CURSOR_DRAG		XC_cross)
set_default(CF_CURSOR_WAITKEY		XC_icon)
set_default(CF_STDISP_MIN_SZ		8)

find_package(Lua51 REQUIRED)

configure_file(config.h.in config.h)
